Translation 01rnaseq gene
openbiox/Awesome-Bioinformatics-Workflow-Chinese pull request #21
Opened 2019-07-07 10:09 UTC by asdwl

翻译 01 rnaseq 基因

2019-07-27 09:28 UTC, ShixiangWang requested changes

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +title: "RNA-seq 工作流程: 基因水平的探索性分析和差异表达分析"
「gene-level exploratory analysis and differential expression」> 「工作流程: 基因水平的探索性和差异表达分析」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> + 这里我们使用 Bioconductor 包执行一个端到端的基因水平 RNA-seq 差异表达分析流程。我们将从FASTQ     文件开始，展示其如何与参考基因组比对，如何准备每个样本中每个基因的 RNA-seq 片段的计数矩阵。我们会进行探索性数据分析（EDA）以完成质量评估，并且为了探索样本之间的关系，执行差异基因表达分析，最后对结果进行可视化。
「Here we walk through an end-to-end gene-level RNA-seq differential expression
  workflow using Bioconductor packages.  We will start from the FASTQ files,
  show how these were aligned to the reference genome, and prepare a count
  matrix which tallies the number of RNA-seq reads/fragments within each gene
  for each sample.  We will perform exploratory data analysis (EDA) for quality
  assessment and to explore the relationship between samples, perform
  differential gene expression analysis, and visually explore the results.」

> 

「这里我们使用 Bioconductor 平台的软件包执行一个端到端的基因水平 RNA-seq 差异表达分析流程。我们将从FASTQ     文件开始，展示其如何与参考基因组比对，如何准备每个样本中每个基因的 RNA-seq 片段的计数矩阵。我们会进行探索性数据分析（EDA）以完成质量评估。并且，为了探索样本之间的关系，我们将执行差异基因表达分析和可视化。」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +Bioconductor 有许多用于分析高通量测序数据的包, 如 RNA（RNA-seq）测序等。
「Bioconductor has many packages which support analysis of
high-throughput sequence 
data, including RNA sequencing (RNA-seq).」

>

「Bioconductor 有许多软件包可用于分析高通量测序数据, 包括 RNA（RNA-seq）测序。

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +我们在这个工作流中使用的包包括由 Bioconductor 核心团队维护的核心包，用来导入
「在」 > 「将在」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +通过每6个月一次的发布计划，bioconductor 项目可以确保所有发布的包在整体上运行流畅。
「bioconductor」 > 「Bioconductor」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +（这也是 “conductor” 一词的隐喻）。本工作流程中使用的包用
「整体上运行流畅。（这也是 “conductor” 一词的隐喻）。」
>
「整体上运行流畅（这也是 “conductor” 一词的隐喻）。」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +*library* 函数加载，并可以通过以下链接安装
library -> library()

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +此工作流程的已发布（但基本相似）版本，包含有审阅报告和评论见
一个包含有审阅报告和评审意见的公开发表版本（与本文基本相似）参见

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +如果您对此工作流程或 Bioconductor 软件有任何疑问，请将这些发布到
这些 => 它

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +[@Himes2014RNASeq]。糖皮质激素用于，诸如，减少哮喘病人的呼吸道炎症。实验中，
「糖皮质激素用于，诸如，减少哮喘病人的呼吸道炎症。」=>「糖皮质激素用于诸如呼吸道炎症中以减少病人哮喘。」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +四个原代的人呼吸道平滑肌细胞系用 1μmol 地塞米松处理 18 小时，每个细胞系都有一个处理的样本
「四个原代的人呼吸道平滑肌细胞系」=>「四个人呼吸道平滑肌原代细胞系」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +那些基于计数的统计方法，例如
那些可以去掉，后面的包名分隔要用中文顿号

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +[Salmon](https://combine-lab.github.io/salmon/) [@Patro2017Salmon]，
分隔用顿号

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +通常会存储在一个[SAM/BAM](http://samtools.github.io/hts-specs)格式的文件。
「SAM/BAM」前后加空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +来将我们当前实验的 reads 和 Ensemblrelease 75 [@Flicek2014Ensembl] 人类参考基
Ensembl release 75

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +Read Archive）下载了FASTQ文件，
FASTQ 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +的比对文件太大了（每个样本大约几个GB），并且计算每个样本的片段数都需要10-30分钟，因此我们
GB 前，10-30分钟前后加空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +选取了 reads 的一个子集用于演示。我们会使用这些文件来演示如何从BAM文件中建立一个计数矩阵。
BAM 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +R函数 *system.file* 用于查找包中的文件在你的计算机中上的安装路径。R一般把外部数据，比如
「包中的文件在你的计算机中上的安装路径」 => 「你的计算机中已安装包文件的路径」

R 后加空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +`r Biocpkg("Rsamtools")` 包给BAM文件提供了一个R接口，其中的 *BamFileList* 函数指定应用于
R 前后加空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +这里的文件。这里我们也指出了关于如何处理BAM文件的细节，比如一次只能处理200万的 reads，键入
BAM 前后空格，200 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
>  *tximport*          | `r Biocpkg("tximport")`                              | R/Bioconductor | list of matrices       | *DESeqDataSetFromTximport*
表格未翻译？

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +那么可以用 *makeTxDbFromGRanges* 函数导入一个预扫描好的 GFT 文件。
GFT => GTF

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +这里我们演示从 GFT 文件处加载 *TxDb* 对象：
GTF

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +我们用一个长度为 0 的字符矢量来说明没有一个序列（染色体）是环状的。
矢量改为 向量比较合适，后者通用。

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +我们在 `features` 和 `reads` 之外还指定了许多的参数。参数 `mode` 表示那一种
哪一种

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +的 *Counting reads with summarizeOverlaps* 使用指南的图 1。
这个指南名字翻译是否更好？

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +将一对reads只计算一次。
reads 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +然而，有些链特异性的实验会存在一些 reads hi对齐到基因的负链上的情况。
hi?

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +## SummarizedExperiment 查看
查看 应删除

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +*SummarizedExperiment* 图解如上，在最新的 Bioconductor 文章中有z关于它的讨论
z 多余

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +`rowRanges` 在打印时,只展示第一个 *GRanges*，并告诉我们还有19个元素：
「`rowRanges` 在打印时,只展示第一个 *GRanges*，并告诉我们还有19个元素：」
=>
「`rowRanges` 在打印时只展示第一个 *GRanges*，这里告诉我们还有19个元素：」

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +`rowRanges`也包含与 `metadata` 槽中的基因模型的构建有关的元数据。
\`前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +这里我们使用`str`这个R函数来简洁的展示metadata。
英文前后空格，\`前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +`colData`插槽目前还是空的，而它应该包含所有的 meta 数据。因为我们使用 `sampleTable`
\`前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
>  `r Biocpkg("limma")` with the voom method [@Law2014Voom],
没翻译完

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +分析需求。此外，Bioconductor有通用性的数据类（如 *SummarizedExperiment* ）可用于在包之
Bioconductor 后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +间转移数据。此外，Bionconductor的核心类提供了一些有用的功能函数：例如，对一个 *SummarizedExperiment*
同上评论

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> + 的行或列取子集或者重排序，会自动对相应的 *rowRanges*和colData* 也取子集或重排序，从而
和 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +**注意：** 在R中，将因子的第一个水平设为参考水平更加合适。（比如，对照的或者未处理的样本），所以
R 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +* 从一个技术矩阵和一个样本信息表开始
计数

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +本工作流程有两个不同的方向：第一个方向是 *计数值的转换*，这部分是为了可视化的
可视化的 这里  「的」应该去掉

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +上提供了很少信息的数据，VST 和rlog 压缩了低计数值基因之间的差异。
rlog 左侧空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +RNA-seq分析一个有效的第一步通常是评估样本之间的相似性：哪些样本彼此相似，哪些是不
seq 后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +注意我们已经改变了距离矩阵中的行名，现在的行名是处理类型-病人的编号，
这里 处理类型-病人的编号 加引号 「处理类型-病人的编号」查看起来会更清楚

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +X轴是数据点差异最大的方向。这个方向的样本的值记为 *PC1* 。y轴是数据点差异第二大方向
X 轴 => x 轴

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +另一个和 PCA 图很相似的图，可以用基于 R 的 *multidimensional scaling* (MDS)
multidimensional scaling 多维尺度变换

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +表达改变了。这个值是一个以 2 为底的 log 值：例如，log2 倍数变化为1.5 的意思是基因
1.5 前空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +如果我们认为 *p* 值低于0.05的这一基因列表是差异表达的，那么该列表应该包含多达
0.05 前后空格

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +值，该值回答了以下问题：如果一个经检验为显著的基因，它的校正后 *p* 值小于等于这个基因
这段解释很难理解，我看原文也不太好翻译，建议咨询或讨论下。

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +**样本间 VST 转换值相关性热图**
这种算是小标题吗？应该与下面空一行，不然markdown 显示效果会有问题的吧？

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +独立性过滤软件使用 `r Biocpkg("genefilter")` 包中的 *DESeq2* ，
翻译有问题，原文是说 DESeq2 的独立性验证功能来自 genefilter 包

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +# 时间进程实验
翻译成 时序 可能更好

2019-07-27 09:28 UTC, ShixiangWang commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +在 0 时之后的一个或更多的时间点变现出了特定压力效应的基因。注意，在两中压力中
两种

2019-07-27 09:29 UTC, ShixiangWang commented
主要是 排版问题，少量的有关翻译问题。

2019-08-12 11:40 UTC, asdwl commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +本工作流程有两个不同的方向：第一个方向是 *计数值的转换*，这部分是为了可视化的
「的」改成了「地」，感觉更为通顺。

2019-08-12 12:00 UTC, asdwl commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +**样本间 VST 转换值相关性热图**
这是个图的标题，后面紧跟着的那段话是解释该图的。英文原版中就是这样排版的，觉得还是保持这样比较好

2019-08-14 15:28 UTC, merged

2019-08-30 22:09 UTC, hjuinj reviewed
翻译大体上非常不错，在此建议了一些小的改动

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> + 这里我们使用 Bioconductor 包执行一个端到端的基因水平 RNA-seq 差异表达分析流程。我们将从FASTQ     文件开始，展示其如何与参考基因组比对，如何准备每个样本中每个基因的 RNA-seq 片段的计数矩阵。我们会进行探索性数据分析（EDA）以完成质量评估，并且为了探索样本之间的关系，执行差异基因表达分析，最后对结果进行可视化。
剔除FASTQ 后的空格

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +Bioconductor 有许多用于分析高通量测序数据的包, 如 RNA（RNA-seq）测序等。
Bioconductor 加粗

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +我们在这个工作流中使用的包包括由 Bioconductor 核心团队维护的核心包，用来导入
Bioconductor 加粗

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +通过每6个月一次的发布计划，bioconductor 项目可以确保所有发布的包在整体上运行流畅。
Bioconductor 加粗

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +如果您对此工作流程或 Bioconductor 软件有任何疑问，请将这些发布到
Bioconductor 加粗

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +四个原代的人呼吸道平滑肌细胞系用 1μmol 地塞米松处理 18 小时，每个细胞系都有一个处理的样本
[1μmol] > [1 μmol]

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +[@Himes2014RNASeq]。糖皮质激素用于，诸如，减少哮喘病人的呼吸道炎症。实验中，
[糖皮质激素用于，诸如，减少哮喘病人的呼吸道炎症。] > [糖皮质激素被用于诸如减少哮喘病人的呼吸道炎症。]

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +是 fragments）。类似的，对于其他类型的实验， 矩阵的行可以对应于诸如：结合位点（ChIP-Seq），
[对于其他类型的实验， 矩阵的行可以]>[对于其他类型的实验，矩阵的行可以]  (多余空格)

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +期望的输入数据是从 RNA-seq 等高通量测序实验中获得的，一个整数格式的矩阵。
[期望的输入数据是从 RNA-seq 等高通量测序实验中获得的，一个整数格式的矩阵。]>[所需的输入数据是一个整数格式的矩阵，这类数据可从如 RNA-seq 等高通量测序实验中获得的。]

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +***SummarizedExperiment* 对象的构成。** `assay` （粉色块）
`【***SummarizedExperiment* 对象的构成。**】》【** *SummarizedExperiment* 对象的构成。**】
三个星号相连应该会导致这里以下所有文字都加粗了`

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +`colData` 插槽目前还是空的，而它应该包含所有的 meta 数据。因为我们使用 `sampleTable`
【meta 数据】》【元数据】

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +这里我们使用 `str` 这个 R 函数来简洁的展示 metadata。
[这个 R 函数来简洁的展示 metadata]>[这个 R 函数来简洁的展示 metadata (元数据)]

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +各种不同的统计学方法对 RNA-seq 进行了大量的生物学重复，这有助于用户决定使用哪些工具是最合适的，
`【@Schurch2016How [compared performance](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/27022035/) of different statistical methods	各种不同的统计学方法对 RNA-seq 进行了大量的生物学重复】 》 【@Schurch2016How 对运用了大量的生物学重复来分析 RNA-seq 的各种不同的统计学方法进行了[比较](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/27022035/) 】`

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +矩阵全部列的 meta 信息。
元信息

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +我们构建的 *DESeqDataSet* 计数矩阵中有许多行值都是 0，此还有许多行的计数值非常小。
[此还有许多行的计数值非常小] > [还有许多行的计数值非常小]

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +映射到 2 维度、平面，他们分散在两个方向上，这两个方向能解释大多数的差异（下图所示）。
[映射到 2 维度、平面，]>[映射到 2 维度平面，]

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +因为 `res` 是一个 *DataFrame* 对象，所以它的列名的含义就是它的 meta 数据。
元数据

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +总之，一个变量的任何两个水平之间的比较结果可以用 *results* 的 `contrast` 参数提取到。
【总之】》【总体而言】 （我觉得总之过于口语化）

2019-08-30 22:09 UTC, hjuinj commented on BiocWorkflow_todo/01rnaseqGene_en.Rmd
> +这个是用于*人类*（“Hs”）的物种注释包，集成在 *AnnotationDbi* 数据包（“db”）中，
[人类] > [智人]